# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

required = [
  "golang.org/x/tools/cmd/goimports",
  "golang.org/x/lint/golint",
  "honnef.co/go/tools/cmd/gosimple",
  "honnef.co/go/tools/cmd/staticcheck",
  "honnef.co/go/tools/cmd/unused",
  "github.com/favclip/jwg",
  "github.com/favclip/qbg"
]

[[constraint]]
  branch = "master"
  name = "google.golang.org/appengine"

[prune]
  go-tests = true
